version: "3"

services:
  web:
    build: .
    container_name: adesalwa

    command: gunicorn adeproject.wsgi:application --bind 0.0.0.0:9003

    volumes:
      - .:/app
    ports:
      - "9003:9003"