# Generated by Django 3.2.8 on 2021-10-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name_plural': 'Artikel'},
        ),
    ]
