# Generated by Django 3.2.8 on 2021-10-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_kategori_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={},
        ),
    ]
